/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DepolarRouteImport } from './routes/depolar'
import { Route as GerceklesenRouteImport } from './routes/gerceklesen'
import { Route as KayitlarRouteImport } from './routes/kayitlar'
import { Route as MakinelerRouteImport } from './routes/makineler'
import { Route as PlanlamaRouteImport } from './routes/planlama'
import { Route as ReferanslarRouteImport } from './routes/referanslar'
import { Route as SiparislerRouteImport } from './routes/siparisler'
import { Route as StoklarRouteImport } from './routes/stoklar'
import { Route as TakvimRouteImport } from './routes/takvim'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DepolarRoute = DepolarRouteImport.update({
  id: '/depolar',
  path: '/depolar',
  getParentRoute: () => rootRouteImport,
} as any)
const GerceklesenRoute = GerceklesenRouteImport.update({
  id: '/gerceklesen',
  path: '/gerceklesen',
  getParentRoute: () => rootRouteImport,
} as any)
const KayitlarRoute = KayitlarRouteImport.update({
  id: '/kayitlar',
  path: '/kayitlar',
  getParentRoute: () => rootRouteImport,
} as any)
const MakinelerRoute = MakinelerRouteImport.update({
  id: '/makineler',
  path: '/makineler',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanlamaRoute = PlanlamaRouteImport.update({
  id: '/planlama',
  path: '/planlama',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferanslarRoute = ReferanslarRouteImport.update({
  id: '/referanslar',
  path: '/referanslar',
  getParentRoute: () => rootRouteImport,
} as any)
const SiparislerRoute = SiparislerRouteImport.update({
  id: '/siparisler',
  path: '/siparisler',
  getParentRoute: () => rootRouteImport,
} as any)
const StoklarRoute = StoklarRouteImport.update({
  id: '/stoklar',
  path: '/stoklar',
  getParentRoute: () => rootRouteImport,
} as any)
const TakvimRoute = TakvimRouteImport.update({
  id: '/takvim',
  path: '/takvim',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/depolar': typeof DepolarRoute
  '/gerceklesen': typeof GerceklesenRoute
  '/kayitlar': typeof KayitlarRoute
  '/makineler': typeof MakinelerRoute
  '/planlama': typeof PlanlamaRoute
  '/referanslar': typeof ReferanslarRoute
  '/siparisler': typeof SiparislerRoute
  '/stoklar': typeof StoklarRoute
  '/takvim': typeof TakvimRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/depolar': typeof DepolarRoute
  '/gerceklesen': typeof GerceklesenRoute
  '/kayitlar': typeof KayitlarRoute
  '/makineler': typeof MakinelerRoute
  '/planlama': typeof PlanlamaRoute
  '/referanslar': typeof ReferanslarRoute
  '/siparisler': typeof SiparislerRoute
  '/stoklar': typeof StoklarRoute
  '/takvim': typeof TakvimRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/depolar': typeof DepolarRoute
  '/gerceklesen': typeof GerceklesenRoute
  '/kayitlar': typeof KayitlarRoute
  '/makineler': typeof MakinelerRoute
  '/planlama': typeof PlanlamaRoute
  '/referanslar': typeof ReferanslarRoute
  '/siparisler': typeof SiparislerRoute
  '/stoklar': typeof StoklarRoute
  '/takvim': typeof TakvimRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/depolar'
    | '/gerceklesen'
    | '/kayitlar'
    | '/makineler'
    | '/planlama'
    | '/referanslar'
    | '/siparisler'
    | '/stoklar'
    | '/takvim'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/depolar'
    | '/gerceklesen'
    | '/kayitlar'
    | '/makineler'
    | '/planlama'
    | '/referanslar'
    | '/siparisler'
    | '/stoklar'
    | '/takvim'
  id:
    | '__root__'
    | '/'
    | '/depolar'
    | '/gerceklesen'
    | '/kayitlar'
    | '/makineler'
    | '/planlama'
    | '/referanslar'
    | '/siparisler'
    | '/stoklar'
    | '/takvim'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DepolarRoute: typeof DepolarRoute
  GerceklesenRoute: typeof GerceklesenRoute
  KayitlarRoute: typeof KayitlarRoute
  MakinelerRoute: typeof MakinelerRoute
  PlanlamaRoute: typeof PlanlamaRoute
  ReferanslarRoute: typeof ReferanslarRoute
  SiparislerRoute: typeof SiparislerRoute
  StoklarRoute: typeof StoklarRoute
  TakvimRoute: typeof TakvimRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depolar': {
      id: '/depolar'
      path: '/depolar'
      fullPath: '/depolar'
      preLoaderRoute: typeof DepolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerceklesen': {
      id: '/gerceklesen'
      path: '/gerceklesen'
      fullPath: '/gerceklesen'
      preLoaderRoute: typeof GerceklesenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kayitlar': {
      id: '/kayitlar'
      path: '/kayitlar'
      fullPath: '/kayitlar'
      preLoaderRoute: typeof KayitlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/makineler': {
      id: '/makineler'
      path: '/makineler'
      fullPath: '/makineler'
      preLoaderRoute: typeof MakinelerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planlama': {
      id: '/planlama'
      path: '/planlama'
      fullPath: '/planlama'
      preLoaderRoute: typeof PlanlamaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referanslar': {
      id: '/referanslar'
      path: '/referanslar'
      fullPath: '/referanslar'
      preLoaderRoute: typeof ReferanslarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siparisler': {
      id: '/siparisler'
      path: '/siparisler'
      fullPath: '/siparisler'
      preLoaderRoute: typeof SiparislerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stoklar': {
      id: '/stoklar'
      path: '/stoklar'
      fullPath: '/stoklar'
      preLoaderRoute: typeof StoklarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/takvim': {
      id: '/takvim'
      path: '/takvim'
      fullPath: '/takvim'
      preLoaderRoute: typeof TakvimRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DepolarRoute: DepolarRoute,
  GerceklesenRoute: GerceklesenRoute,
  KayitlarRoute: KayitlarRoute,
  MakinelerRoute: MakinelerRoute,
  PlanlamaRoute: PlanlamaRoute,
  ReferanslarRoute: ReferanslarRoute,
  SiparislerRoute: SiparislerRoute,
  StoklarRoute: StoklarRoute,
  TakvimRoute: TakvimRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
