/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DepolarRouteImport } from './routes/depolar'
import { Route as DieFollowupRouteImport } from './routes/die-followup'
import { Route as GerceklesenRouteImport } from './routes/gerceklesen'
import { Route as KaliplarRouteImport } from './routes/kaliplar'
import { Route as KalipproblemRouteImport } from './routes/kalipproblem'
import { Route as KayitlarRouteImport } from './routes/kayitlar'
import { Route as KpiRouteImport } from './routes/kpi'
import { Route as MachineFollowupRouteImport } from './routes/machine-followup'
import { Route as MakinelerRouteImport } from './routes/makineler'
import { Route as OeeRouteImport } from './routes/oee'
import { Route as PerformansRouteImport } from './routes/performans'
import { Route as PlanlamaRouteImport } from './routes/planlama'
import { Route as PlanlogicRouteImport } from './routes/planlogic'
import { Route as PlanningexpertRouteImport } from './routes/planningexpert'
import { Route as PresbakimRouteImport } from './routes/presbakim'
import { Route as ReferanslarRouteImport } from './routes/referanslar'
import { Route as SapdataRouteImport } from './routes/sapdata'
import { Route as SiparislerRouteImport } from './routes/siparisler'
import { Route as StoklarRouteImport } from './routes/stoklar'
import { Route as TakvimRouteImport } from './routes/takvim'
import { Route as TaniRouteImport } from './routes/tani'
import { Route as YonetimRouteImport } from './routes/yonetim'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DepolarRoute = DepolarRouteImport.update({
  id: '/depolar',
  path: '/depolar',
  getParentRoute: () => rootRouteImport,
} as any)
const DieFollowupRoute = DieFollowupRouteImport.update({
  id: '/die-followup',
  path: '/die-followup',
  getParentRoute: () => rootRouteImport,
} as any)
const GerceklesenRoute = GerceklesenRouteImport.update({
  id: '/gerceklesen',
  path: '/gerceklesen',
  getParentRoute: () => rootRouteImport,
} as any)
const KaliplarRoute = KaliplarRouteImport.update({
  id: '/kaliplar',
  path: '/kaliplar',
  getParentRoute: () => rootRouteImport,
} as any)
const KalipproblemRoute = KalipproblemRouteImport.update({
  id: '/kalipproblem',
  path: '/kalipproblem',
  getParentRoute: () => rootRouteImport,
} as any)
const KayitlarRoute = KayitlarRouteImport.update({
  id: '/kayitlar',
  path: '/kayitlar',
  getParentRoute: () => rootRouteImport,
} as any)
const KpiRoute = KpiRouteImport.update({
  id: '/kpi',
  path: '/kpi',
  getParentRoute: () => rootRouteImport,
} as any)
const MachineFollowupRoute = MachineFollowupRouteImport.update({
  id: '/machine-followup',
  path: '/machine-followup',
  getParentRoute: () => rootRouteImport,
} as any)
const MakinelerRoute = MakinelerRouteImport.update({
  id: '/makineler',
  path: '/makineler',
  getParentRoute: () => rootRouteImport,
} as any)
const OeeRoute = OeeRouteImport.update({
  id: '/oee',
  path: '/oee',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformansRoute = PerformansRouteImport.update({
  id: '/performans',
  path: '/performans',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanlamaRoute = PlanlamaRouteImport.update({
  id: '/planlama',
  path: '/planlama',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanlogicRoute = PlanlogicRouteImport.update({
  id: '/planlogic',
  path: '/planlogic',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningexpertRoute = PlanningexpertRouteImport.update({
  id: '/planningexpert',
  path: '/planningexpert',
  getParentRoute: () => rootRouteImport,
} as any)
const PresbakimRoute = PresbakimRouteImport.update({
  id: '/presbakim',
  path: '/presbakim',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferanslarRoute = ReferanslarRouteImport.update({
  id: '/referanslar',
  path: '/referanslar',
  getParentRoute: () => rootRouteImport,
} as any)
const SapdataRoute = SapdataRouteImport.update({
  id: '/sapdata',
  path: '/sapdata',
  getParentRoute: () => rootRouteImport,
} as any)
const SiparislerRoute = SiparislerRouteImport.update({
  id: '/siparisler',
  path: '/siparisler',
  getParentRoute: () => rootRouteImport,
} as any)
const StoklarRoute = StoklarRouteImport.update({
  id: '/stoklar',
  path: '/stoklar',
  getParentRoute: () => rootRouteImport,
} as any)
const TakvimRoute = TakvimRouteImport.update({
  id: '/takvim',
  path: '/takvim',
  getParentRoute: () => rootRouteImport,
} as any)
const TaniRoute = TaniRouteImport.update({
  id: '/tani',
  path: '/tani',
  getParentRoute: () => rootRouteImport,
} as any)
const YonetimRoute = YonetimRouteImport.update({
  id: '/yonetim',
  path: '/yonetim',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/depolar': typeof DepolarRoute
  '/die-followup': typeof DieFollowupRoute
  '/gerceklesen': typeof GerceklesenRoute
  '/kaliplar': typeof KaliplarRoute
  '/kalipproblem': typeof KalipproblemRoute
  '/kayitlar': typeof KayitlarRoute
  '/kpi': typeof KpiRoute
  '/machine-followup': typeof MachineFollowupRoute
  '/makineler': typeof MakinelerRoute
  '/oee': typeof OeeRoute
  '/performans': typeof PerformansRoute
  '/planlama': typeof PlanlamaRoute
  '/planlogic': typeof PlanlogicRoute
  '/planningexpert': typeof PlanningexpertRoute
  '/presbakim': typeof PresbakimRoute
  '/referanslar': typeof ReferanslarRoute
  '/sapdata': typeof SapdataRoute
  '/siparisler': typeof SiparislerRoute
  '/stoklar': typeof StoklarRoute
  '/takvim': typeof TakvimRoute
  '/tani': typeof TaniRoute
  '/yonetim': typeof YonetimRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/depolar': typeof DepolarRoute
  '/die-followup': typeof DieFollowupRoute
  '/gerceklesen': typeof GerceklesenRoute
  '/kaliplar': typeof KaliplarRoute
  '/kalipproblem': typeof KalipproblemRoute
  '/kayitlar': typeof KayitlarRoute
  '/kpi': typeof KpiRoute
  '/machine-followup': typeof MachineFollowupRoute
  '/makineler': typeof MakinelerRoute
  '/oee': typeof OeeRoute
  '/performans': typeof PerformansRoute
  '/planlama': typeof PlanlamaRoute
  '/planlogic': typeof PlanlogicRoute
  '/planningexpert': typeof PlanningexpertRoute
  '/presbakim': typeof PresbakimRoute
  '/referanslar': typeof ReferanslarRoute
  '/sapdata': typeof SapdataRoute
  '/siparisler': typeof SiparislerRoute
  '/stoklar': typeof StoklarRoute
  '/takvim': typeof TakvimRoute
  '/tani': typeof TaniRoute
  '/yonetim': typeof YonetimRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/depolar': typeof DepolarRoute
  '/die-followup': typeof DieFollowupRoute
  '/gerceklesen': typeof GerceklesenRoute
  '/kaliplar': typeof KaliplarRoute
  '/kalipproblem': typeof KalipproblemRoute
  '/kayitlar': typeof KayitlarRoute
  '/kpi': typeof KpiRoute
  '/machine-followup': typeof MachineFollowupRoute
  '/makineler': typeof MakinelerRoute
  '/oee': typeof OeeRoute
  '/performans': typeof PerformansRoute
  '/planlama': typeof PlanlamaRoute
  '/planlogic': typeof PlanlogicRoute
  '/planningexpert': typeof PlanningexpertRoute
  '/presbakim': typeof PresbakimRoute
  '/referanslar': typeof ReferanslarRoute
  '/sapdata': typeof SapdataRoute
  '/siparisler': typeof SiparislerRoute
  '/stoklar': typeof StoklarRoute
  '/takvim': typeof TakvimRoute
  '/tani': typeof TaniRoute
  '/yonetim': typeof YonetimRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/depolar'
    | '/die-followup'
    | '/gerceklesen'
    | '/kaliplar'
    | '/kalipproblem'
    | '/kayitlar'
    | '/kpi'
    | '/machine-followup'
    | '/makineler'
    | '/oee'
    | '/performans'
    | '/planlama'
    | '/planlogic'
    | '/planningexpert'
    | '/presbakim'
    | '/referanslar'
    | '/sapdata'
    | '/siparisler'
    | '/stoklar'
    | '/takvim'
    | '/tani'
    | '/yonetim'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/depolar'
    | '/die-followup'
    | '/gerceklesen'
    | '/kaliplar'
    | '/kalipproblem'
    | '/kayitlar'
    | '/kpi'
    | '/machine-followup'
    | '/makineler'
    | '/oee'
    | '/performans'
    | '/planlama'
    | '/planlogic'
    | '/planningexpert'
    | '/presbakim'
    | '/referanslar'
    | '/sapdata'
    | '/siparisler'
    | '/stoklar'
    | '/takvim'
    | '/tani'
    | '/yonetim'
  id:
    | '__root__'
    | '/'
    | '/depolar'
    | '/die-followup'
    | '/gerceklesen'
    | '/kaliplar'
    | '/kalipproblem'
    | '/kayitlar'
    | '/kpi'
    | '/machine-followup'
    | '/makineler'
    | '/oee'
    | '/performans'
    | '/planlama'
    | '/planlogic'
    | '/planningexpert'
    | '/presbakim'
    | '/referanslar'
    | '/sapdata'
    | '/siparisler'
    | '/stoklar'
    | '/takvim'
    | '/tani'
    | '/yonetim'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DepolarRoute: typeof DepolarRoute
  DieFollowupRoute: typeof DieFollowupRoute
  GerceklesenRoute: typeof GerceklesenRoute
  KaliplarRoute: typeof KaliplarRoute
  KalipproblemRoute: typeof KalipproblemRoute
  KayitlarRoute: typeof KayitlarRoute
  KpiRoute: typeof KpiRoute
  MachineFollowupRoute: typeof MachineFollowupRoute
  MakinelerRoute: typeof MakinelerRoute
  OeeRoute: typeof OeeRoute
  PerformansRoute: typeof PerformansRoute
  PlanlamaRoute: typeof PlanlamaRoute
  PlanlogicRoute: typeof PlanlogicRoute
  PlanningexpertRoute: typeof PlanningexpertRoute
  PresbakimRoute: typeof PresbakimRoute
  ReferanslarRoute: typeof ReferanslarRoute
  SapdataRoute: typeof SapdataRoute
  SiparislerRoute: typeof SiparislerRoute
  StoklarRoute: typeof StoklarRoute
  TakvimRoute: typeof TakvimRoute
  TaniRoute: typeof TaniRoute
  YonetimRoute: typeof YonetimRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depolar': {
      id: '/depolar'
      path: '/depolar'
      fullPath: '/depolar'
      preLoaderRoute: typeof DepolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/die-followup': {
      id: '/die-followup'
      path: '/die-followup'
      fullPath: '/die-followup'
      preLoaderRoute: typeof DieFollowupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerceklesen': {
      id: '/gerceklesen'
      path: '/gerceklesen'
      fullPath: '/gerceklesen'
      preLoaderRoute: typeof GerceklesenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kaliplar': {
      id: '/kaliplar'
      path: '/kaliplar'
      fullPath: '/kaliplar'
      preLoaderRoute: typeof KaliplarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalipproblem': {
      id: '/kalipproblem'
      path: '/kalipproblem'
      fullPath: '/kalipproblem'
      preLoaderRoute: typeof KalipproblemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kayitlar': {
      id: '/kayitlar'
      path: '/kayitlar'
      fullPath: '/kayitlar'
      preLoaderRoute: typeof KayitlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kpi': {
      id: '/kpi'
      path: '/kpi'
      fullPath: '/kpi'
      preLoaderRoute: typeof KpiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machine-followup': {
      id: '/machine-followup'
      path: '/machine-followup'
      fullPath: '/machine-followup'
      preLoaderRoute: typeof MachineFollowupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/makineler': {
      id: '/makineler'
      path: '/makineler'
      fullPath: '/makineler'
      preLoaderRoute: typeof MakinelerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oee': {
      id: '/oee'
      path: '/oee'
      fullPath: '/oee'
      preLoaderRoute: typeof OeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performans': {
      id: '/performans'
      path: '/performans'
      fullPath: '/performans'
      preLoaderRoute: typeof PerformansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planlama': {
      id: '/planlama'
      path: '/planlama'
      fullPath: '/planlama'
      preLoaderRoute: typeof PlanlamaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planlogic': {
      id: '/planlogic'
      path: '/planlogic'
      fullPath: '/planlogic'
      preLoaderRoute: typeof PlanlogicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planningexpert': {
      id: '/planningexpert'
      path: '/planningexpert'
      fullPath: '/planningexpert'
      preLoaderRoute: typeof PlanningexpertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presbakim': {
      id: '/presbakim'
      path: '/presbakim'
      fullPath: '/presbakim'
      preLoaderRoute: typeof PresbakimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referanslar': {
      id: '/referanslar'
      path: '/referanslar'
      fullPath: '/referanslar'
      preLoaderRoute: typeof ReferanslarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sapdata': {
      id: '/sapdata'
      path: '/sapdata'
      fullPath: '/sapdata'
      preLoaderRoute: typeof SapdataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siparisler': {
      id: '/siparisler'
      path: '/siparisler'
      fullPath: '/siparisler'
      preLoaderRoute: typeof SiparislerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stoklar': {
      id: '/stoklar'
      path: '/stoklar'
      fullPath: '/stoklar'
      preLoaderRoute: typeof StoklarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/takvim': {
      id: '/takvim'
      path: '/takvim'
      fullPath: '/takvim'
      preLoaderRoute: typeof TakvimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tani': {
      id: '/tani'
      path: '/tani'
      fullPath: '/tani'
      preLoaderRoute: typeof TaniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yonetim': {
      id: '/yonetim'
      path: '/yonetim'
      fullPath: '/yonetim'
      preLoaderRoute: typeof YonetimRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DepolarRoute: DepolarRoute,
  DieFollowupRoute: DieFollowupRoute,
  GerceklesenRoute: GerceklesenRoute,
  KaliplarRoute: KaliplarRoute,
  KalipproblemRoute: KalipproblemRoute,
  KayitlarRoute: KayitlarRoute,
  KpiRoute: KpiRoute,
  MachineFollowupRoute: MachineFollowupRoute,
  MakinelerRoute: MakinelerRoute,
  OeeRoute: OeeRoute,
  PerformansRoute: PerformansRoute,
  PlanlamaRoute: PlanlamaRoute,
  PlanlogicRoute: PlanlogicRoute,
  PlanningexpertRoute: PlanningexpertRoute,
  PresbakimRoute: PresbakimRoute,
  ReferanslarRoute: ReferanslarRoute,
  SapdataRoute: SapdataRoute,
  SiparislerRoute: SiparislerRoute,
  StoklarRoute: StoklarRoute,
  TakvimRoute: TakvimRoute,
  TaniRoute: TaniRoute,
  YonetimRoute: YonetimRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
