/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlarmsRouteImport } from './routes/alarms'
import { Route as CapacityRouteImport } from './routes/capacity'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as DepolarRouteImport } from './routes/depolar'
import { Route as GerceklesenRouteImport } from './routes/gerceklesen'
import { Route as HammaddeRouteImport } from './routes/hammadde'
import { Route as KaliplarRouteImport } from './routes/kaliplar'
import { Route as KalipproblemRouteImport } from './routes/kalipproblem'
import { Route as KayitlarRouteImport } from './routes/kayitlar'
import { Route as MakinelerRouteImport } from './routes/makineler'
import { Route as PerformansRouteImport } from './routes/performans'
import { Route as PlanlamaRouteImport } from './routes/planlama'
import { Route as PlanlogicRouteImport } from './routes/planlogic'
import { Route as PlanningexpertRouteImport } from './routes/planningexpert'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as PresbakimRouteImport } from './routes/presbakim'
import { Route as ReferanslarRouteImport } from './routes/referanslar'
import { Route as SapdataRouteImport } from './routes/sapdata'
import { Route as SiparislerRouteImport } from './routes/siparisler'
import { Route as StoklarRouteImport } from './routes/stoklar'
import { Route as TakvimRouteImport } from './routes/takvim'
import { Route as TaniRouteImport } from './routes/tani'
import { Route as YonetimRouteImport } from './routes/yonetim'
import { Route as DieFollowupIndexRouteImport } from './routes/die-followup/index'
import { Route as DieFollowupMaintenanceRouteImport } from './routes/die-followup/maintenance'
import { Route as DieFollowupProblemsRouteImport } from './routes/die-followup/problems'
import { Route as DieFollowupReportsRouteImport } from './routes/die-followup/reports'
import { Route as KpiIndexRouteImport } from './routes/kpi/index'
import { Route as MachineFollowupIndexRouteImport } from './routes/machine-followup/index'
import { Route as MachineFollowupBreakdownsRouteImport } from './routes/machine-followup/breakdowns'
import { Route as MachineFollowupMaintenanceRouteImport } from './routes/machine-followup/maintenance'
import { Route as MachineFollowupReportsRouteImport } from './routes/machine-followup/reports'
import { Route as OeeIndexRouteImport } from './routes/oee/index'
import { Route as OeeDataRouteImport } from './routes/oee/data'
import { Route as OeeGuideRouteImport } from './routes/oee/guide'
import { Route as OeeLossesRouteImport } from './routes/oee/losses'
import { Route as OeeSettingsRouteImport } from './routes/oee/settings'
import { Route as KpiMonthlyDashboardRouteImport } from './routes/kpi/monthly/dashboard'
import { Route as KpiMonthlyEntryRouteImport } from './routes/kpi/monthly/entry'
import { Route as KpiWeeklyDashboardRouteImport } from './routes/kpi/weekly/dashboard'
import { Route as KpiWeeklyEntryRouteImport } from './routes/kpi/weekly/entry'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlarmsRoute = AlarmsRouteImport.update({
  id: '/alarms',
  path: '/alarms',
  getParentRoute: () => rootRouteImport,
} as any)
const CapacityRoute = CapacityRouteImport.update({
  id: '/capacity',
  path: '/capacity',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const DepolarRoute = DepolarRouteImport.update({
  id: '/depolar',
  path: '/depolar',
  getParentRoute: () => rootRouteImport,
} as any)
const GerceklesenRoute = GerceklesenRouteImport.update({
  id: '/gerceklesen',
  path: '/gerceklesen',
  getParentRoute: () => rootRouteImport,
} as any)
const HammaddeRoute = HammaddeRouteImport.update({
  id: '/hammadde',
  path: '/hammadde',
  getParentRoute: () => rootRouteImport,
} as any)
const KaliplarRoute = KaliplarRouteImport.update({
  id: '/kaliplar',
  path: '/kaliplar',
  getParentRoute: () => rootRouteImport,
} as any)
const KalipproblemRoute = KalipproblemRouteImport.update({
  id: '/kalipproblem',
  path: '/kalipproblem',
  getParentRoute: () => rootRouteImport,
} as any)
const KayitlarRoute = KayitlarRouteImport.update({
  id: '/kayitlar',
  path: '/kayitlar',
  getParentRoute: () => rootRouteImport,
} as any)
const MakinelerRoute = MakinelerRouteImport.update({
  id: '/makineler',
  path: '/makineler',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformansRoute = PerformansRouteImport.update({
  id: '/performans',
  path: '/performans',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanlamaRoute = PlanlamaRouteImport.update({
  id: '/planlama',
  path: '/planlama',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanlogicRoute = PlanlogicRouteImport.update({
  id: '/planlogic',
  path: '/planlogic',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningexpertRoute = PlanningexpertRouteImport.update({
  id: '/planningexpert',
  path: '/planningexpert',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PresbakimRoute = PresbakimRouteImport.update({
  id: '/presbakim',
  path: '/presbakim',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferanslarRoute = ReferanslarRouteImport.update({
  id: '/referanslar',
  path: '/referanslar',
  getParentRoute: () => rootRouteImport,
} as any)
const SapdataRoute = SapdataRouteImport.update({
  id: '/sapdata',
  path: '/sapdata',
  getParentRoute: () => rootRouteImport,
} as any)
const SiparislerRoute = SiparislerRouteImport.update({
  id: '/siparisler',
  path: '/siparisler',
  getParentRoute: () => rootRouteImport,
} as any)
const StoklarRoute = StoklarRouteImport.update({
  id: '/stoklar',
  path: '/stoklar',
  getParentRoute: () => rootRouteImport,
} as any)
const TakvimRoute = TakvimRouteImport.update({
  id: '/takvim',
  path: '/takvim',
  getParentRoute: () => rootRouteImport,
} as any)
const TaniRoute = TaniRouteImport.update({
  id: '/tani',
  path: '/tani',
  getParentRoute: () => rootRouteImport,
} as any)
const YonetimRoute = YonetimRouteImport.update({
  id: '/yonetim',
  path: '/yonetim',
  getParentRoute: () => rootRouteImport,
} as any)
const DieFollowupIndexRoute = DieFollowupIndexRouteImport.update({
  id: '/die-followup/',
  path: '/die-followup/',
  getParentRoute: () => rootRouteImport,
} as any)
const DieFollowupMaintenanceRoute = DieFollowupMaintenanceRouteImport.update({
  id: '/die-followup/maintenance',
  path: '/die-followup/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const DieFollowupProblemsRoute = DieFollowupProblemsRouteImport.update({
  id: '/die-followup/problems',
  path: '/die-followup/problems',
  getParentRoute: () => rootRouteImport,
} as any)
const DieFollowupReportsRoute = DieFollowupReportsRouteImport.update({
  id: '/die-followup/reports',
  path: '/die-followup/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const KpiIndexRoute = KpiIndexRouteImport.update({
  id: '/kpi/',
  path: '/kpi/',
  getParentRoute: () => rootRouteImport,
} as any)
const MachineFollowupIndexRoute = MachineFollowupIndexRouteImport.update({
  id: '/machine-followup/',
  path: '/machine-followup/',
  getParentRoute: () => rootRouteImport,
} as any)
const MachineFollowupBreakdownsRoute =
  MachineFollowupBreakdownsRouteImport.update({
    id: '/machine-followup/breakdowns',
    path: '/machine-followup/breakdowns',
    getParentRoute: () => rootRouteImport,
  } as any)
const MachineFollowupMaintenanceRoute =
  MachineFollowupMaintenanceRouteImport.update({
    id: '/machine-followup/maintenance',
    path: '/machine-followup/maintenance',
    getParentRoute: () => rootRouteImport,
  } as any)
const MachineFollowupReportsRoute = MachineFollowupReportsRouteImport.update({
  id: '/machine-followup/reports',
  path: '/machine-followup/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const OeeIndexRoute = OeeIndexRouteImport.update({
  id: '/oee/',
  path: '/oee/',
  getParentRoute: () => rootRouteImport,
} as any)
const OeeDataRoute = OeeDataRouteImport.update({
  id: '/oee/data',
  path: '/oee/data',
  getParentRoute: () => rootRouteImport,
} as any)
const OeeGuideRoute = OeeGuideRouteImport.update({
  id: '/oee/guide',
  path: '/oee/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const OeeLossesRoute = OeeLossesRouteImport.update({
  id: '/oee/losses',
  path: '/oee/losses',
  getParentRoute: () => rootRouteImport,
} as any)
const OeeSettingsRoute = OeeSettingsRouteImport.update({
  id: '/oee/settings',
  path: '/oee/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const KpiMonthlyDashboardRoute = KpiMonthlyDashboardRouteImport.update({
  id: '/kpi/monthly/dashboard',
  path: '/kpi/monthly/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const KpiMonthlyEntryRoute = KpiMonthlyEntryRouteImport.update({
  id: '/kpi/monthly/entry',
  path: '/kpi/monthly/entry',
  getParentRoute: () => rootRouteImport,
} as any)
const KpiWeeklyDashboardRoute = KpiWeeklyDashboardRouteImport.update({
  id: '/kpi/weekly/dashboard',
  path: '/kpi/weekly/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const KpiWeeklyEntryRoute = KpiWeeklyEntryRouteImport.update({
  id: '/kpi/weekly/entry',
  path: '/kpi/weekly/entry',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alarms': typeof AlarmsRoute
  '/capacity': typeof CapacityRoute
  '/compare': typeof CompareRoute
  '/depolar': typeof DepolarRoute
  '/gerceklesen': typeof GerceklesenRoute
  '/hammadde': typeof HammaddeRoute
  '/kaliplar': typeof KaliplarRoute
  '/kalipproblem': typeof KalipproblemRoute
  '/kayitlar': typeof KayitlarRoute
  '/makineler': typeof MakinelerRoute
  '/performans': typeof PerformansRoute
  '/planlama': typeof PlanlamaRoute
  '/planlogic': typeof PlanlogicRoute
  '/planningexpert': typeof PlanningexpertRoute
  '/platform': typeof PlatformRoute
  '/presbakim': typeof PresbakimRoute
  '/referanslar': typeof ReferanslarRoute
  '/sapdata': typeof SapdataRoute
  '/siparisler': typeof SiparislerRoute
  '/stoklar': typeof StoklarRoute
  '/takvim': typeof TakvimRoute
  '/tani': typeof TaniRoute
  '/yonetim': typeof YonetimRoute
  '/die-followup/maintenance': typeof DieFollowupMaintenanceRoute
  '/die-followup/problems': typeof DieFollowupProblemsRoute
  '/die-followup/reports': typeof DieFollowupReportsRoute
  '/machine-followup/breakdowns': typeof MachineFollowupBreakdownsRoute
  '/machine-followup/maintenance': typeof MachineFollowupMaintenanceRoute
  '/machine-followup/reports': typeof MachineFollowupReportsRoute
  '/oee/data': typeof OeeDataRoute
  '/oee/guide': typeof OeeGuideRoute
  '/oee/losses': typeof OeeLossesRoute
  '/oee/settings': typeof OeeSettingsRoute
  '/die-followup/': typeof DieFollowupIndexRoute
  '/kpi/': typeof KpiIndexRoute
  '/machine-followup/': typeof MachineFollowupIndexRoute
  '/oee/': typeof OeeIndexRoute
  '/kpi/monthly/dashboard': typeof KpiMonthlyDashboardRoute
  '/kpi/monthly/entry': typeof KpiMonthlyEntryRoute
  '/kpi/weekly/dashboard': typeof KpiWeeklyDashboardRoute
  '/kpi/weekly/entry': typeof KpiWeeklyEntryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alarms': typeof AlarmsRoute
  '/capacity': typeof CapacityRoute
  '/compare': typeof CompareRoute
  '/depolar': typeof DepolarRoute
  '/gerceklesen': typeof GerceklesenRoute
  '/hammadde': typeof HammaddeRoute
  '/kaliplar': typeof KaliplarRoute
  '/kalipproblem': typeof KalipproblemRoute
  '/kayitlar': typeof KayitlarRoute
  '/makineler': typeof MakinelerRoute
  '/performans': typeof PerformansRoute
  '/planlama': typeof PlanlamaRoute
  '/planlogic': typeof PlanlogicRoute
  '/planningexpert': typeof PlanningexpertRoute
  '/platform': typeof PlatformRoute
  '/presbakim': typeof PresbakimRoute
  '/referanslar': typeof ReferanslarRoute
  '/sapdata': typeof SapdataRoute
  '/siparisler': typeof SiparislerRoute
  '/stoklar': typeof StoklarRoute
  '/takvim': typeof TakvimRoute
  '/tani': typeof TaniRoute
  '/yonetim': typeof YonetimRoute
  '/die-followup/maintenance': typeof DieFollowupMaintenanceRoute
  '/die-followup/problems': typeof DieFollowupProblemsRoute
  '/die-followup/reports': typeof DieFollowupReportsRoute
  '/machine-followup/breakdowns': typeof MachineFollowupBreakdownsRoute
  '/machine-followup/maintenance': typeof MachineFollowupMaintenanceRoute
  '/machine-followup/reports': typeof MachineFollowupReportsRoute
  '/oee/data': typeof OeeDataRoute
  '/oee/guide': typeof OeeGuideRoute
  '/oee/losses': typeof OeeLossesRoute
  '/oee/settings': typeof OeeSettingsRoute
  '/die-followup': typeof DieFollowupIndexRoute
  '/kpi': typeof KpiIndexRoute
  '/machine-followup': typeof MachineFollowupIndexRoute
  '/oee': typeof OeeIndexRoute
  '/kpi/monthly/dashboard': typeof KpiMonthlyDashboardRoute
  '/kpi/monthly/entry': typeof KpiMonthlyEntryRoute
  '/kpi/weekly/dashboard': typeof KpiWeeklyDashboardRoute
  '/kpi/weekly/entry': typeof KpiWeeklyEntryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alarms': typeof AlarmsRoute
  '/capacity': typeof CapacityRoute
  '/compare': typeof CompareRoute
  '/depolar': typeof DepolarRoute
  '/gerceklesen': typeof GerceklesenRoute
  '/hammadde': typeof HammaddeRoute
  '/kaliplar': typeof KaliplarRoute
  '/kalipproblem': typeof KalipproblemRoute
  '/kayitlar': typeof KayitlarRoute
  '/makineler': typeof MakinelerRoute
  '/performans': typeof PerformansRoute
  '/planlama': typeof PlanlamaRoute
  '/planlogic': typeof PlanlogicRoute
  '/planningexpert': typeof PlanningexpertRoute
  '/platform': typeof PlatformRoute
  '/presbakim': typeof PresbakimRoute
  '/referanslar': typeof ReferanslarRoute
  '/sapdata': typeof SapdataRoute
  '/siparisler': typeof SiparislerRoute
  '/stoklar': typeof StoklarRoute
  '/takvim': typeof TakvimRoute
  '/tani': typeof TaniRoute
  '/yonetim': typeof YonetimRoute
  '/die-followup/maintenance': typeof DieFollowupMaintenanceRoute
  '/die-followup/problems': typeof DieFollowupProblemsRoute
  '/die-followup/reports': typeof DieFollowupReportsRoute
  '/machine-followup/breakdowns': typeof MachineFollowupBreakdownsRoute
  '/machine-followup/maintenance': typeof MachineFollowupMaintenanceRoute
  '/machine-followup/reports': typeof MachineFollowupReportsRoute
  '/oee/data': typeof OeeDataRoute
  '/oee/guide': typeof OeeGuideRoute
  '/oee/losses': typeof OeeLossesRoute
  '/oee/settings': typeof OeeSettingsRoute
  '/die-followup/': typeof DieFollowupIndexRoute
  '/kpi/': typeof KpiIndexRoute
  '/machine-followup/': typeof MachineFollowupIndexRoute
  '/oee/': typeof OeeIndexRoute
  '/kpi/monthly/dashboard': typeof KpiMonthlyDashboardRoute
  '/kpi/monthly/entry': typeof KpiMonthlyEntryRoute
  '/kpi/weekly/dashboard': typeof KpiWeeklyDashboardRoute
  '/kpi/weekly/entry': typeof KpiWeeklyEntryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alarms'
    | '/capacity'
    | '/compare'
    | '/depolar'
    | '/gerceklesen'
    | '/hammadde'
    | '/kaliplar'
    | '/kalipproblem'
    | '/kayitlar'
    | '/makineler'
    | '/performans'
    | '/planlama'
    | '/planlogic'
    | '/planningexpert'
    | '/platform'
    | '/presbakim'
    | '/referanslar'
    | '/sapdata'
    | '/siparisler'
    | '/stoklar'
    | '/takvim'
    | '/tani'
    | '/yonetim'
    | '/die-followup/maintenance'
    | '/die-followup/problems'
    | '/die-followup/reports'
    | '/machine-followup/breakdowns'
    | '/machine-followup/maintenance'
    | '/machine-followup/reports'
    | '/oee/data'
    | '/oee/guide'
    | '/oee/losses'
    | '/oee/settings'
    | '/die-followup/'
    | '/kpi/'
    | '/machine-followup/'
    | '/oee/'
    | '/kpi/monthly/dashboard'
    | '/kpi/monthly/entry'
    | '/kpi/weekly/dashboard'
    | '/kpi/weekly/entry'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alarms'
    | '/capacity'
    | '/compare'
    | '/depolar'
    | '/gerceklesen'
    | '/hammadde'
    | '/kaliplar'
    | '/kalipproblem'
    | '/kayitlar'
    | '/makineler'
    | '/performans'
    | '/planlama'
    | '/planlogic'
    | '/planningexpert'
    | '/platform'
    | '/presbakim'
    | '/referanslar'
    | '/sapdata'
    | '/siparisler'
    | '/stoklar'
    | '/takvim'
    | '/tani'
    | '/yonetim'
    | '/die-followup/maintenance'
    | '/die-followup/problems'
    | '/die-followup/reports'
    | '/machine-followup/breakdowns'
    | '/machine-followup/maintenance'
    | '/machine-followup/reports'
    | '/oee/data'
    | '/oee/guide'
    | '/oee/losses'
    | '/oee/settings'
    | '/die-followup'
    | '/kpi'
    | '/machine-followup'
    | '/oee'
    | '/kpi/monthly/dashboard'
    | '/kpi/monthly/entry'
    | '/kpi/weekly/dashboard'
    | '/kpi/weekly/entry'
  id:
    | '__root__'
    | '/'
    | '/alarms'
    | '/capacity'
    | '/compare'
    | '/depolar'
    | '/gerceklesen'
    | '/hammadde'
    | '/kaliplar'
    | '/kalipproblem'
    | '/kayitlar'
    | '/makineler'
    | '/performans'
    | '/planlama'
    | '/planlogic'
    | '/planningexpert'
    | '/platform'
    | '/presbakim'
    | '/referanslar'
    | '/sapdata'
    | '/siparisler'
    | '/stoklar'
    | '/takvim'
    | '/tani'
    | '/yonetim'
    | '/die-followup/maintenance'
    | '/die-followup/problems'
    | '/die-followup/reports'
    | '/machine-followup/breakdowns'
    | '/machine-followup/maintenance'
    | '/machine-followup/reports'
    | '/oee/data'
    | '/oee/guide'
    | '/oee/losses'
    | '/oee/settings'
    | '/die-followup/'
    | '/kpi/'
    | '/machine-followup/'
    | '/oee/'
    | '/kpi/monthly/dashboard'
    | '/kpi/monthly/entry'
    | '/kpi/weekly/dashboard'
    | '/kpi/weekly/entry'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlarmsRoute: typeof AlarmsRoute
  CapacityRoute: typeof CapacityRoute
  CompareRoute: typeof CompareRoute
  DepolarRoute: typeof DepolarRoute
  GerceklesenRoute: typeof GerceklesenRoute
  HammaddeRoute: typeof HammaddeRoute
  KaliplarRoute: typeof KaliplarRoute
  KalipproblemRoute: typeof KalipproblemRoute
  KayitlarRoute: typeof KayitlarRoute
  MakinelerRoute: typeof MakinelerRoute
  PerformansRoute: typeof PerformansRoute
  PlanlamaRoute: typeof PlanlamaRoute
  PlanlogicRoute: typeof PlanlogicRoute
  PlanningexpertRoute: typeof PlanningexpertRoute
  PlatformRoute: typeof PlatformRoute
  PresbakimRoute: typeof PresbakimRoute
  ReferanslarRoute: typeof ReferanslarRoute
  SapdataRoute: typeof SapdataRoute
  SiparislerRoute: typeof SiparislerRoute
  StoklarRoute: typeof StoklarRoute
  TakvimRoute: typeof TakvimRoute
  TaniRoute: typeof TaniRoute
  YonetimRoute: typeof YonetimRoute
  DieFollowupMaintenanceRoute: typeof DieFollowupMaintenanceRoute
  DieFollowupProblemsRoute: typeof DieFollowupProblemsRoute
  DieFollowupReportsRoute: typeof DieFollowupReportsRoute
  MachineFollowupBreakdownsRoute: typeof MachineFollowupBreakdownsRoute
  MachineFollowupMaintenanceRoute: typeof MachineFollowupMaintenanceRoute
  MachineFollowupReportsRoute: typeof MachineFollowupReportsRoute
  OeeDataRoute: typeof OeeDataRoute
  OeeGuideRoute: typeof OeeGuideRoute
  OeeLossesRoute: typeof OeeLossesRoute
  OeeSettingsRoute: typeof OeeSettingsRoute
  DieFollowupIndexRoute: typeof DieFollowupIndexRoute
  KpiIndexRoute: typeof KpiIndexRoute
  MachineFollowupIndexRoute: typeof MachineFollowupIndexRoute
  OeeIndexRoute: typeof OeeIndexRoute
  KpiMonthlyDashboardRoute: typeof KpiMonthlyDashboardRoute
  KpiMonthlyEntryRoute: typeof KpiMonthlyEntryRoute
  KpiWeeklyDashboardRoute: typeof KpiWeeklyDashboardRoute
  KpiWeeklyEntryRoute: typeof KpiWeeklyEntryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alarms': {
      id: '/alarms'
      path: '/alarms'
      fullPath: '/alarms'
      preLoaderRoute: typeof AlarmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capacity': {
      id: '/capacity'
      path: '/capacity'
      fullPath: '/capacity'
      preLoaderRoute: typeof CapacityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depolar': {
      id: '/depolar'
      path: '/depolar'
      fullPath: '/depolar'
      preLoaderRoute: typeof DepolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerceklesen': {
      id: '/gerceklesen'
      path: '/gerceklesen'
      fullPath: '/gerceklesen'
      preLoaderRoute: typeof GerceklesenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hammadde': {
      id: '/hammadde'
      path: '/hammadde'
      fullPath: '/hammadde'
      preLoaderRoute: typeof HammaddeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kaliplar': {
      id: '/kaliplar'
      path: '/kaliplar'
      fullPath: '/kaliplar'
      preLoaderRoute: typeof KaliplarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalipproblem': {
      id: '/kalipproblem'
      path: '/kalipproblem'
      fullPath: '/kalipproblem'
      preLoaderRoute: typeof KalipproblemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kayitlar': {
      id: '/kayitlar'
      path: '/kayitlar'
      fullPath: '/kayitlar'
      preLoaderRoute: typeof KayitlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/makineler': {
      id: '/makineler'
      path: '/makineler'
      fullPath: '/makineler'
      preLoaderRoute: typeof MakinelerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performans': {
      id: '/performans'
      path: '/performans'
      fullPath: '/performans'
      preLoaderRoute: typeof PerformansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planlama': {
      id: '/planlama'
      path: '/planlama'
      fullPath: '/planlama'
      preLoaderRoute: typeof PlanlamaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planlogic': {
      id: '/planlogic'
      path: '/planlogic'
      fullPath: '/planlogic'
      preLoaderRoute: typeof PlanlogicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planningexpert': {
      id: '/planningexpert'
      path: '/planningexpert'
      fullPath: '/planningexpert'
      preLoaderRoute: typeof PlanningexpertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presbakim': {
      id: '/presbakim'
      path: '/presbakim'
      fullPath: '/presbakim'
      preLoaderRoute: typeof PresbakimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referanslar': {
      id: '/referanslar'
      path: '/referanslar'
      fullPath: '/referanslar'
      preLoaderRoute: typeof ReferanslarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sapdata': {
      id: '/sapdata'
      path: '/sapdata'
      fullPath: '/sapdata'
      preLoaderRoute: typeof SapdataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siparisler': {
      id: '/siparisler'
      path: '/siparisler'
      fullPath: '/siparisler'
      preLoaderRoute: typeof SiparislerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stoklar': {
      id: '/stoklar'
      path: '/stoklar'
      fullPath: '/stoklar'
      preLoaderRoute: typeof StoklarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/takvim': {
      id: '/takvim'
      path: '/takvim'
      fullPath: '/takvim'
      preLoaderRoute: typeof TakvimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tani': {
      id: '/tani'
      path: '/tani'
      fullPath: '/tani'
      preLoaderRoute: typeof TaniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yonetim': {
      id: '/yonetim'
      path: '/yonetim'
      fullPath: '/yonetim'
      preLoaderRoute: typeof YonetimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/die-followup/': {
      id: '/die-followup/'
      path: '/die-followup'
      fullPath: '/die-followup/'
      preLoaderRoute: typeof DieFollowupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/die-followup/maintenance': {
      id: '/die-followup/maintenance'
      path: '/die-followup/maintenance'
      fullPath: '/die-followup/maintenance'
      preLoaderRoute: typeof DieFollowupMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/die-followup/problems': {
      id: '/die-followup/problems'
      path: '/die-followup/problems'
      fullPath: '/die-followup/problems'
      preLoaderRoute: typeof DieFollowupProblemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/die-followup/reports': {
      id: '/die-followup/reports'
      path: '/die-followup/reports'
      fullPath: '/die-followup/reports'
      preLoaderRoute: typeof DieFollowupReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kpi/': {
      id: '/kpi/'
      path: '/kpi'
      fullPath: '/kpi/'
      preLoaderRoute: typeof KpiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machine-followup/': {
      id: '/machine-followup/'
      path: '/machine-followup'
      fullPath: '/machine-followup/'
      preLoaderRoute: typeof MachineFollowupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machine-followup/breakdowns': {
      id: '/machine-followup/breakdowns'
      path: '/machine-followup/breakdowns'
      fullPath: '/machine-followup/breakdowns'
      preLoaderRoute: typeof MachineFollowupBreakdownsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machine-followup/maintenance': {
      id: '/machine-followup/maintenance'
      path: '/machine-followup/maintenance'
      fullPath: '/machine-followup/maintenance'
      preLoaderRoute: typeof MachineFollowupMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machine-followup/reports': {
      id: '/machine-followup/reports'
      path: '/machine-followup/reports'
      fullPath: '/machine-followup/reports'
      preLoaderRoute: typeof MachineFollowupReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oee/': {
      id: '/oee/'
      path: '/oee'
      fullPath: '/oee/'
      preLoaderRoute: typeof OeeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oee/data': {
      id: '/oee/data'
      path: '/oee/data'
      fullPath: '/oee/data'
      preLoaderRoute: typeof OeeDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oee/guide': {
      id: '/oee/guide'
      path: '/oee/guide'
      fullPath: '/oee/guide'
      preLoaderRoute: typeof OeeGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oee/losses': {
      id: '/oee/losses'
      path: '/oee/losses'
      fullPath: '/oee/losses'
      preLoaderRoute: typeof OeeLossesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oee/settings': {
      id: '/oee/settings'
      path: '/oee/settings'
      fullPath: '/oee/settings'
      preLoaderRoute: typeof OeeSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kpi/monthly/dashboard': {
      id: '/kpi/monthly/dashboard'
      path: '/kpi/monthly/dashboard'
      fullPath: '/kpi/monthly/dashboard'
      preLoaderRoute: typeof KpiMonthlyDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kpi/monthly/entry': {
      id: '/kpi/monthly/entry'
      path: '/kpi/monthly/entry'
      fullPath: '/kpi/monthly/entry'
      preLoaderRoute: typeof KpiMonthlyEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kpi/weekly/dashboard': {
      id: '/kpi/weekly/dashboard'
      path: '/kpi/weekly/dashboard'
      fullPath: '/kpi/weekly/dashboard'
      preLoaderRoute: typeof KpiWeeklyDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kpi/weekly/entry': {
      id: '/kpi/weekly/entry'
      path: '/kpi/weekly/entry'
      fullPath: '/kpi/weekly/entry'
      preLoaderRoute: typeof KpiWeeklyEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlarmsRoute: AlarmsRoute,
  CapacityRoute: CapacityRoute,
  CompareRoute: CompareRoute,
  DepolarRoute: DepolarRoute,
  GerceklesenRoute: GerceklesenRoute,
  HammaddeRoute: HammaddeRoute,
  KaliplarRoute: KaliplarRoute,
  KalipproblemRoute: KalipproblemRoute,
  KayitlarRoute: KayitlarRoute,
  MakinelerRoute: MakinelerRoute,
  PerformansRoute: PerformansRoute,
  PlanlamaRoute: PlanlamaRoute,
  PlanlogicRoute: PlanlogicRoute,
  PlanningexpertRoute: PlanningexpertRoute,
  PlatformRoute: PlatformRoute,
  PresbakimRoute: PresbakimRoute,
  ReferanslarRoute: ReferanslarRoute,
  SapdataRoute: SapdataRoute,
  SiparislerRoute: SiparislerRoute,
  StoklarRoute: StoklarRoute,
  TakvimRoute: TakvimRoute,
  TaniRoute: TaniRoute,
  YonetimRoute: YonetimRoute,
  DieFollowupMaintenanceRoute: DieFollowupMaintenanceRoute,
  DieFollowupProblemsRoute: DieFollowupProblemsRoute,
  DieFollowupReportsRoute: DieFollowupReportsRoute,
  MachineFollowupBreakdownsRoute: MachineFollowupBreakdownsRoute,
  MachineFollowupMaintenanceRoute: MachineFollowupMaintenanceRoute,
  MachineFollowupReportsRoute: MachineFollowupReportsRoute,
  OeeDataRoute: OeeDataRoute,
  OeeGuideRoute: OeeGuideRoute,
  OeeLossesRoute: OeeLossesRoute,
  OeeSettingsRoute: OeeSettingsRoute,
  DieFollowupIndexRoute: DieFollowupIndexRoute,
  KpiIndexRoute: KpiIndexRoute,
  MachineFollowupIndexRoute: MachineFollowupIndexRoute,
  OeeIndexRoute: OeeIndexRoute,
  KpiMonthlyDashboardRoute: KpiMonthlyDashboardRoute,
  KpiMonthlyEntryRoute: KpiMonthlyEntryRoute,
  KpiWeeklyDashboardRoute: KpiWeeklyDashboardRoute,
  KpiWeeklyEntryRoute: KpiWeeklyEntryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
